package com.sayanthrock.githubrock.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color
import com.sayanthrock.githubrock.data.settings.ThemeStyle

internal fun ColorScheme.applyRockStyle(style:ThemeStyle,dark:Boolean):ColorScheme=when(style){
 ThemeStyle.Clean->this
 ThemeStyle.LiquidGlass->copy(surface=surface.copy(alpha=.94f),surfaceContainer=surfaceContainer.copy(alpha=.90f),surfaceContainerHigh=surfaceContainerHigh.copy(alpha=.92f),surfaceVariant=surfaceVariant.copy(alpha=.88f),outlineVariant=primary.copy(alpha=.20f))
 ThemeStyle.Studio->copy(background=if(dark)Color(0xFF0B0E12)else Color(0xFFF6F7F9),surface=if(dark)Color(0xFF11161D)else Color.White,surfaceContainer=if(dark)Color(0xFF151B23)else Color(0xFFF0F2F5),surfaceContainerHigh=if(dark)Color(0xFF1B222C)else Color(0xFFE7EBF0),outlineVariant=if(dark)Color(0xFF313A46)else Color(0xFFD4D9E0))
 ThemeStyle.Midnight->copy(background=if(dark)Color(0xFF070B14)else Color(0xFFF4F7FC),surface=if(dark)Color(0xFF0D1422)else Color.White,surfaceContainer=if(dark)Color(0xFF121C2D)else Color(0xFFEAF0FA),surfaceContainerHigh=if(dark)Color(0xFF19263A)else Color(0xFFDDE7F5),outlineVariant=primary.copy(alpha=.28f))
 ThemeStyle.Aurora->copy(background=if(dark)Color(0xFF07110F)else Color(0xFFF4FBF8),surface=if(dark)Color(0xFF0D1A17)else Color.White,surfaceContainer=if(dark)Color(0xFF13231F)else Color(0xFFE8F6F0),surfaceContainerHigh=if(dark)Color(0xFF1A2E29)else Color(0xFFD9EEE6),outlineVariant=tertiary.copy(alpha=.30f))
 ThemeStyle.HighContrast->copy(background=if(dark)Color.Black else Color.White,surface=if(dark)Color(0xFF050505)else Color.White,surfaceContainer=if(dark)Color(0xFF0D0D0D)else Color(0xFFF4F4F4),surfaceContainerHigh=if(dark)Color(0xFF161616)else Color(0xFFEAEAEA),outline=if(dark)Color.White else Color.Black,outlineVariant=if(dark)Color(0xFFBDBDBD)else Color(0xFF2B2B2B),onBackground=if(dark)Color.White else Color.Black,onSurface=if(dark)Color.White else Color.Black,onSurfaceVariant=if(dark)Color(0xFFE3E3E3)else Color(0xFF222222))
 ThemeStyle.Obsidian->copy(background=if(dark)Color(0xFF07080A)else Color(0xFFF5F6F8),surface=if(dark)Color(0xFF0D0F12)else Color(0xFFFCFCFD),surfaceVariant=if(dark)Color(0xFF111419)else Color(0xFFF0F2F5),surfaceContainerLowest=if(dark)Color(0xFF050608)else Color.White,surfaceContainerLow=if(dark)Color(0xFF0A0C0F)else Color(0xFFF7F8FA),surfaceContainer=if(dark)Color(0xFF12151A)else Color(0xFFF0F2F5),surfaceContainerHigh=if(dark)Color(0xFF191D23)else Color(0xFFE7EAF0),surfaceContainerHighest=if(dark)Color(0xFF222730)else Color(0xFFDCE1E8),outline=if(dark)Color(0xFF343B45)else Color(0xFFB8C0CA),outlineVariant=if(dark)Color(0xFF242A32)else Color(0xFFD9DEE5),onBackground=if(dark)Color(0xFFF1F3F5)else Color(0xFF16191D),onSurface=if(dark)Color(0xFFF1F3F5)else Color(0xFF16191D),onSurfaceVariant=if(dark)Color(0xFFAAB2BD)else Color(0xFF59636E))
internal fun ColorScheme.applyTrueBlack(dark:Boolean,enabled:Boolean)=if(!dark||!enabled)this else copy(background=Color.Black,surfaceContainerLowest=Color.Black)
