package com.sayanthrock.githubrock.ui.theme

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.sayanthrock.githubrock.data.settings.ThemeStyle

internal fun rockDarkColors(a: AccentTonalPalette)=darkColorScheme(primary=a.darkPrimary,onPrimary=a.darkOnPrimary,primaryContainer=a.darkContainer,onPrimaryContainer=a.darkOnContainer,secondary=Color(0xFFB6C2CF),onSecondary=Color(0xFF1B242D),tertiary=RockGreen,background=Color.Black,surface=Color(0xFF080808),surfaceVariant=Color(0xFF0D0D0D),surfaceContainerLowest=Color.Black,surfaceContainerLow=Color(0xFF080808),surfaceContainer=Color(0xFF101010),surfaceContainerHigh=Color(0xFF171717),surfaceContainerHighest=Color(0xFF202020),outline=RockDarkBorder,outlineVariant=Color(0xFF252B33),error=RockRed,onBackground=RockDarkText,onSurface=RockDarkText,onSurfaceVariant=RockDarkMuted)
internal fun rockLightColors(a: AccentTonalPalette)=lightColorScheme(primary=a.lightPrimary,onPrimary=a.lightOnPrimary,primaryContainer=a.lightContainer,onPrimaryContainer=a.lightOnContainer,secondary=Color(0xFF59636E),onSecondary=Color.White,tertiary=RockLightGreen,background=RockLightBackground,surface=RockLightSurface,surfaceVariant=RockLightSurfaceHigh,surfaceContainerLowest=RockLightSurface,surfaceContainerLow=Color(0xFFF0F3F6),surfaceContainer=RockLightSurface,surfaceContainerHigh=RockLightSurfaceHigh,surfaceContainerHighest=Color(0xFFDDE2E7),outline=RockLightBorder,outlineVariant=Color(0xFFE1E5EA),error=RockLightRed,onBackground=RockLightText,onSurface=RockLightText,onSurfaceVariant=RockLightMuted)
internal fun rockShapes(s:ThemeStyle)=when(s){ThemeStyle.Clean->Shapes(extraSmall=RoundedCornerShape(6.dp),small=RoundedCornerShape(9.dp),medium=RoundedCornerShape(12.dp),large=RoundedCornerShape(16.dp),extraLarge=RoundedCornerShape(24.dp));ThemeStyle.LiquidGlass->Shapes(extraSmall=RoundedCornerShape(12.dp),small=RoundedCornerShape(16.dp),medium=RoundedCornerShape(20.dp),large=RoundedCornerShape(26.dp),extraLarge=RoundedCornerShape(34.dp));ThemeStyle.Studio->Shapes(extraSmall=RoundedCornerShape(4.dp),small=RoundedCornerShape(7.dp),medium=RoundedCornerShape(10.dp),large=RoundedCornerShape(13.dp),extraLarge=RoundedCornerShape(18.dp));ThemeStyle.Midnight->Shapes(extraSmall=RoundedCornerShape(8.dp),small=RoundedCornerShape(12.dp),medium=RoundedCornerShape(16.dp),large=RoundedCornerShape(20.dp),extraLarge=RoundedCornerShape(28.dp));ThemeStyle.Aurora->Shapes(extraSmall=RoundedCornerShape(10.dp),small=RoundedCornerShape(14.dp),medium=RoundedCornerShape(18.dp),large=RoundedCornerShape(24.dp),extraLarge=RoundedCornerShape(32.dp));ThemeStyle.HighContrast->Shapes(extraSmall=RoundedCornerShape(2.dp),small=RoundedCornerShape(4.dp),medium=RoundedCornerShape(6.dp),large=RoundedCornerShape(8.dp),extraLarge=RoundedCornerShape(12.dp));ThemeStyle.Obsidian->Shapes(extraSmall=RoundedCornerShape(7.dp),small=RoundedCornerShape(11.dp),medium=RoundedCornerShape(15.dp),large=RoundedCornerShape(20.dp),extraLarge=RoundedCornerShape(28.dp))}
